service: elmoghany-portfolio

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: us-west-1
  memorySize: 128

functions:
  headers:
    handler: headers.handler
    architecture: x86_64
    events:
      - cloudFront:
          eventType: origin-response
          origin: http://www.elmoghany.com.s3-website-us-west-1.amazonaws.com
  api:
    handler: index.handler
    architecture: arm64
    events:
      - http:
          path: /
          method: ANY
          cors: true
      - http:
          path: /{proxy+}
          method: ANY
          cors: true
